name: Build
on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*"]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, macos-15]
        addrsize: ["64"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: secondlife/action-autobuild@v5
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v3
        with:
          public: true
